version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8443:8443"
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: ankane/pgvector:latest
    environment:
      POSTGRES_DB: ragaas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
