version: '3.8'
services:
  rag-ass-app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - pgvector
    networks:
      - backend

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rag-ass-app.rule=Host(`${API_URL}`)"
      - "traefik.http.routers.rag-ass-app.entrypoints=websecure"
      - "traefik.http.routers.rag-ass-app.tls.certresolver=myresolver"

  pgvector:
    image: ankane/pgvector:latest
    environment:
      POSTGRES_DB: ragaas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
    external: true
